//
//  Localization.swift
//  Hab' ich wirklich so viel Zeit gespart?
//

import Foundation

// MARK: - Global accessor

/// The currently active language (resolved from the user's setting).
/// Set by LocationManager on launch / when the setting changes.
var currentAppLanguage: AppLanguage = .english

/// Returns the localized string for `key` in the current language,
/// falling back to English if the key is missing.
func L(_ key: String) -> String {
    let lang = currentAppLanguage.resolved
    if let value = translations[lang]?[key] { return value }
    if let value = translations[.english]?[key] { return value }
    return key // last resort: return the key itself
}

/// Returns a localized format string with arguments filled in.
func L(_ key: String, _ args: CVarArg...) -> String {
    let fmt = L(key)
    return String(format: fmt, arguments: args)
}

// MARK: - Translation tables

private let translations: [AppLanguage: [String: String]] = [
    .german: german,
    .english: english,
    .korean: korean,
    .spanish: spanish,
    .italian: italian,
    .dutch: dutch,
    .french: french,
    .romanian: romanian,
    .portuguese: portuguese,
]

// MARK: - German (original)

private let german: [String: String] = [
    // ContentView
    "trafficJamMode": "Staumodus",
    "stop": "Stop",
    "reset": "Reset",

    "referenceFormat": "Referenz: %d %@",
    "timeSaved": "Gesparte Zeit",
    "travelTime": "Fahrzeit",
    "distance": "Strecke",
    "average": "Durchschnitt",
    "extraConsumptionFormat": "Mehrverbrauch ≳%@ %%",
    "workFormat": "Arbeit: %@ / %@ kWh",
    "mehrverbrauchHelp": "Schätzt grob, wie viel mehr Kraftstoff bzw. Energie du durch das Überschreiten der Referenzgeschwindigkeit verbrauchst. Die Berechnung berücksichtigt Luftwiderstand, Rollwiderstand, Höhenunterschiede und Beschleunigung. Da reale Faktoren wie Gangwahl, Windverhältnisse, Motoreffizienz und Reifendruck nicht erfasst werden, dient der Wert nur als Anhaltspunkt.",
    "arbeitHelp": "Mechanische Arbeit in kWh: tatsächlich geleistete Arbeit / Arbeit bei konstanter Referenzgeschwindigkeit. Der Quotient ergibt den Mehrverbrauch.",

    // SettingsView
    "referenceSpeed": "Referenzgeschwindigkeit",
    "referenceFooterFormat": "Zeitersparnis wird berechnet, wenn du schneller als %d %@ fährst.",
    "unit": "Einheit",
    "powerDisplay": "Leistungsanzeige",
    "powerDisplayFooter": "Zeigt den Leistungsbogen und die Skalenmarkierungen im Geschwindigkeitsring an.",
    "vehicle": "Fahrzeug",
    "vehicleSwipeHint": "Wische seitwärts, um zwischen Fahrzeugen zu wechseln oder ein neues hinzuzufügen.",
    "deleteVehicle": "Dieses Fahrzeug löschen",
    "settings": "Einstellungen",
    "done": "Fertig",
    "name": "Name",
    "power": "Leistung",
    "measured": "Gemessen",
    "vehicleMass": "Fahrzeugmasse",
    "frontalArea": "Stirnfläche",
    "dragCoefficient": "Cw-Wert",
    "rollingResistance": "Rollwiderstand",
    "electricVehicle": "Elektrofahrzeug",
    "regenEfficiency": "Rekuperationseffizienz",
    "addVehicle": "Fahrzeug hinzufügen",
    "language": "Sprache",
    "vehicleDefaultName": "Auto #%d",

    // HelpView
    "helpTitle": "Lohnt sich das?",
    "helpSubtitleOr": "–oder–",
    "helpSubtitleFull": "Hab' ich wirklich so viel Zeit gespart?",
    "helpSpeed": "Geschwindigkeit",
    "helpSpeedText": "Die App zeigt deine aktuelle Geschwindigkeit per GPS an – wahlweise in km/h oder mph.",
    "helpPower": "Momentanleistung",
    "helpPowerText": "Der farbige Bogen innerhalb des Geschwindigkeitsrings zeigt die aktuelle Motorleistung an. Er ist auf das aktive Fahrzeug skaliert: Bei voller Leistung (Fahrzeugleistung × Antriebsstrang-Wirkungsgrad von 85\u{00A0}%) reicht der Bogen bis zum Ende des grauen Rings. Der rote Bogen (nach rechts) zeigt die tatsächlich geleistete Arbeit; grün (nach links) zeigt Bremsen. Bei Elektrofahrzeugen kennzeichnet helles Grün den per Rekuperation zurückgewonnenen Anteil. Die Markierungen passen sich automatisch an den Leistungsbereich des Fahrzeugs an. Die höchste gemessene Motorleistung wird pro Fahrzeug in den Einstellungen gespeichert und kann dort als Fahrzeugleistung übernommen oder zurückgesetzt werden.",
    "helpTimeSaved": "Gesparte Zeit",
    "helpTimeSavedText": "Immer wenn du schneller als die eingestellte Referenzgeschwindigkeit fährst, berechnet die App, wie viel Zeit du im Vergleich zur Referenzgeschwindigkeit sparst. Zeit unterhalb der Referenz wird nicht abgezogen.",
    "helpExtraConsumption": "Mehrverbrauch",
    "helpExtraConsumptionText": "Schätzt grob, wie viel mehr Kraftstoff bzw. Energie du durch das Überschreiten der Referenzgeschwindigkeit verbrauchst. Die Berechnung berücksichtigt Luftwiderstand, Rollwiderstand, Höhenunterschiede und Beschleunigung. Da reale Faktoren wie Gangwahl, Windverhältnisse, Motoreffizienz und Reifendruck nicht erfasst werden, dient der Wert nur als Anhaltspunkt. Die Parameter des aktiven Fahrzeugs (Masse, Stirnfläche, Cw-Wert usw.) können in den Einstellungen angepasst werden.",
    "helpTravelTime": "Fahrzeit",
    "helpTravelTimeText": "Die Fahrzeit läuft, sobald du schneller als 10 km/h fährst. Sie stoppt automatisch, wenn du länger als zwei Minuten unter 10 km/h bleibst. Im Staumodus wird diese Zeit auf eine Stunde verlängert. Die Wartezeit bis zum automatischen Stopp wird von der Fahrzeit abgezogen. Während der Fahrt bleibt der Bildschirm an; danach darf er sich wie gewohnt ausschalten.",
    "helpDistance": "Strecke",
    "helpDistanceText": "Zeigt die gesamte gefahrene Strecke seit dem letzten Reset an – in Kilometern oder Meilen, je nach Einstellung.",
    "helpAverageSpeed": "Durchschnittsgeschwindigkeit",
    "helpAverageSpeedText": "Die Durchschnittsgeschwindigkeit wird aus der gefahrenen Strecke und der Fahrzeit berechnet.",
    "helpTrafficJam": "Staumodus",
    "helpTrafficJamText": "Aktiviere den Staumodus, wenn du im Stau stehst. Die automatische Stopp-Zeit wird dann von zwei Minuten auf eine Stunde verlängert.",
    "helpStop": "Stop",
    "helpStopText": "Stoppt die Fahrzeit sofort manuell, z.\u{00A0}B. wenn du an deinem Ziel angekommen bist.",
    "helpVehicles": "Fahrzeuge",
    "helpVehiclesText": "Du kannst mehrere Fahrzeuge anlegen. In den Einstellungen wischst du seitwärts zwischen den Fahrzeugen und legst über \u{201E}Fahrzeug hinzufügen\u{201C} ein weiteres an. Jedes Fahrzeug hat einen Namen (ohne Eingabe \u{201E}Auto #x\u{201C}) sowie eigene Parameter wie Leistung, Masse, Stirnfläche und Antriebsart. Die Leistung kann in kW, PS oder HP eingegeben werden. Sind mehrere Fahrzeuge vorhanden, wählst du das aktive Fahrzeug oben in der Mitte über den Fahrzeugnamen aus.",
    "helpSettings": "Einstellungen",
    "helpSettingsText": "Über das Zahnrad oben rechts kannst du die Referenzgeschwindigkeit anpassen, zwischen km/h und mph umschalten und deine Fahrzeuge verwalten.",
    "helpBackground": "Hintergrund",
    "helpBackgroundText": "Die App läuft im Hintergrund weiter und erfasst auch dann Geschwindigkeit und gesparte Zeit, wenn du eine andere App nutzt. Wenn du nicht fährst, reduziert die App automatisch die GPS-Genauigkeit und spart so Akku.",
    "help": "Hilfe",
    "kmhUnit": "km/h",
]

// MARK: - English

private let english: [String: String] = [
    "trafficJamMode": "Stop-and-Go",
    "stop": "Stop",
    "reset": "Reset",

    "referenceFormat": "Reference: %d %@",
    "timeSaved": "Time Saved",
    "travelTime": "Travel Time",
    "distance": "Distance",
    "average": "Average",
    "extraConsumptionFormat": "Extra consumption ≳%@ %%",
    "workFormat": "Work: %@ / %@ kWh",
    "mehrverbrauchHelp": "Roughly estimates how much more fuel or energy you consume by exceeding the reference speed. The calculation considers aerodynamic drag, rolling resistance, elevation changes, and acceleration. Since real-world factors like gear selection, wind conditions, engine efficiency, and tyre pressure are not captured, this value is only an approximation.",
    "arbeitHelp": "Mechanical work in kWh: actual work performed / work at constant reference speed. The quotient gives the extra consumption.",

    "referenceSpeed": "Reference Speed",
    "referenceFooterFormat": "Time savings are calculated when driving faster than %d %@.",
    "unit": "Unit",
    "powerDisplay": "Power Display",
    "powerDisplayFooter": "Shows the power arc and scale markings in the speed ring.",
    "vehicle": "Vehicle",
    "vehicleSwipeHint": "Swipe sideways to switch between vehicles or add a new one.",
    "deleteVehicle": "Delete This Vehicle",
    "settings": "Settings",
    "done": "Done",
    "name": "Name",
    "power": "Power",
    "measured": "Measured",
    "vehicleMass": "Vehicle Mass",
    "frontalArea": "Frontal Area",
    "dragCoefficient": "Drag Coefficient",
    "rollingResistance": "Rolling Resistance",
    "electricVehicle": "Electric Vehicle",
    "regenEfficiency": "Regen Efficiency",
    "addVehicle": "Add Vehicle",
    "language": "Language",
    "vehicleDefaultName": "Car #%d",

    "helpTitle": "Is it worth it?",
    "helpSubtitleOr": "–or–",
    "helpSubtitleFull": "Did I really save that much time?",
    "helpSpeed": "Speed",
    "helpSpeedText": "The app shows your current GPS speed — in kph or mph, depending on your setting.",
    "helpPower": "Instantaneous Power",
    "helpPowerText": "The coloured arc inside the speed ring shows the current engine power. It is scaled to the active vehicle: at full power (vehicle power × 85% drivetrain efficiency) the arc reaches the end of the grey ring. The red arc (to the right) shows work being done; green (to the left) shows braking. For electric vehicles, bright green indicates the portion recovered through regenerative braking. The tick marks adapt automatically to the vehicle's power range. The highest measured engine power is saved per vehicle in Settings and can be adopted as the vehicle's rated power or reset there.",
    "helpTimeSaved": "Time Saved",
    "helpTimeSavedText": "Whenever you drive faster than the set reference speed, the app calculates how much time you save compared to the reference speed. Time below the reference is not subtracted.",
    "helpExtraConsumption": "Extra Consumption",
    "helpExtraConsumptionText": "Roughly estimates how much more fuel or energy you consume by exceeding the reference speed. The calculation considers aerodynamic drag, rolling resistance, elevation changes, and acceleration. Since real-world factors like gear selection, wind conditions, engine efficiency, and tyre pressure are not captured, this value is only an approximation. The active vehicle's parameters (mass, frontal area, drag coefficient, etc.) can be adjusted in Settings.",
    "helpTravelTime": "Travel Time",
    "helpTravelTimeText": "Travel time starts as soon as you drive faster than 10 kph. It stops automatically if you stay below 10 kph for more than two minutes. In stop-and-go mode this time is extended to one hour. The idle wait time is subtracted from the travel time. While driving, the screen stays on; afterwards it can turn off as usual.",
    "helpDistance": "Distance",
    "helpDistanceText": "Shows the total distance driven since the last reset — in kilometres or miles, depending on your setting.",
    "helpAverageSpeed": "Average Speed",
    "helpAverageSpeedText": "The average speed is calculated from the distance driven and the travel time.",
    "helpTrafficJam": "Stop-and-Go Mode",
    "helpTrafficJamText": "Activate stop-and-go mode when you are in stop-and-go traffic. The automatic stop time is then extended from two minutes to one hour.",
    "helpStop": "Stop",
    "helpStopText": "Stops the travel time immediately, e.g. when you have arrived at your destination.",
    "helpVehicles": "Vehicles",
    "helpVehiclesText": "You can create multiple vehicles. In Settings, swipe sideways between vehicles and use \u{201C}Add Vehicle\u{201D} to create another. Each vehicle has a name (defaults to \u{201C}Car #x\u{201D}) and its own parameters such as power, mass, frontal area, and drivetrain type. Power can be entered in kW, PS, or HP. When multiple vehicles exist, you select the active one at the top centre via the vehicle name.",
    "helpSettings": "Settings",
    "helpSettingsText": "Via the gear icon in the top right you can adjust the reference speed, switch between kph and mph, and manage your vehicles.",
    "helpBackground": "Background",
    "helpBackgroundText": "The app continues running in the background, tracking speed and time saved even when you use another app. When you are not driving, the app automatically reduces GPS accuracy to save battery.",
    "help": "Help",
    "kmhUnit": "kph",
]

// MARK: - Korean

private let korean: [String: String] = [
    "trafficJamMode": "정체 모드",
    "stop": "정지",
    "reset": "초기화",

    "referenceFormat": "기준: %d %@",
    "timeSaved": "절약한 시간",
    "travelTime": "주행 시간",
    "distance": "거리",
    "average": "평균",
    "extraConsumptionFormat": "추가 소비 ≳%@ %%",
    "workFormat": "일: %@ / %@ kWh",
    "mehrverbrauchHelp": "기준 속도를 초과하여 소비하는 추가 연료 또는 에너지를 대략적으로 추정합니다. 공기 저항, 구름 저항, 고도 변화 및 가속을 고려합니다. 기어 선택, 바람, 엔진 효율, 타이어 압력 등 실제 요인은 반영되지 않으므로 참고 값입니다.",
    "arbeitHelp": "기계적 일(kWh): 실제 수행된 일 / 기준 속도에서의 일. 비율이 추가 소비량입니다.",

    "referenceSpeed": "기준 속도",
    "referenceFooterFormat": "%d %@ 이상으로 주행할 때 시간 절약이 계산됩니다.",
    "unit": "단위",
    "powerDisplay": "출력 표시",
    "powerDisplayFooter": "속도 링에 출력 호와 눈금을 표시합니다.",
    "vehicle": "차량",
    "vehicleSwipeHint": "좌우로 스와이프하여 차량을 전환하거나 새 차량을 추가하세요.",
    "deleteVehicle": "이 차량 삭제",
    "settings": "설정",
    "done": "완료",
    "name": "이름",
    "power": "출력",
    "measured": "측정값",
    "vehicleMass": "차량 질량",
    "frontalArea": "전면 면적",
    "dragCoefficient": "항력 계수",
    "rollingResistance": "구름 저항",
    "electricVehicle": "전기차",
    "regenEfficiency": "회생 효율",
    "addVehicle": "차량 추가",
    "language": "언어",
    "vehicleDefaultName": "차량 #%d",

    "helpTitle": "그만한 가치가 있을까?",
    "helpSubtitleOr": "–또는–",
    "helpSubtitleFull": "정말 그만큼 시간을 절약했을까?",
    "helpSpeed": "속도",
    "helpSpeedText": "GPS를 통해 현재 속도를 표시합니다 — 설정에 따라 km/h 또는 mph로 표시됩니다.",
    "helpPower": "순간 출력",
    "helpPowerText": "속도 링 안의 색상 호는 현재 엔진 출력을 나타냅니다. 활성 차량에 맞게 조정됩니다: 최대 출력(차량 출력 × 85% 구동계 효율)에서 호가 회색 링 끝까지 도달합니다. 빨간색 호(오른쪽)는 엔진 작업을, 녹색(왼쪽)은 제동을 나타냅니다. 전기차의 경우 밝은 녹색이 회생 제동으로 회수된 부분을 표시합니다. 눈금은 차량의 출력 범위에 자동으로 조정됩니다. 측정된 최고 엔진 출력은 차량별로 설정에 저장되며, 차량 출력으로 적용하거나 초기화할 수 있습니다.",
    "helpTimeSaved": "절약한 시간",
    "helpTimeSavedText": "설정된 기준 속도보다 빠르게 주행할 때마다 기준 속도 대비 절약한 시간을 계산합니다. 기준 속도 이하의 시간은 차감되지 않습니다.",
    "helpExtraConsumption": "추가 소비",
    "helpExtraConsumptionText": "기준 속도를 초과하여 소비하는 추가 연료 또는 에너지를 대략적으로 추정합니다. 공기 저항, 구름 저항, 고도 변화 및 가속을 고려합니다. 실제 요인은 반영되지 않으므로 참고 값입니다. 활성 차량의 매개변수(질량, 전면 면적, 항력 계수 등)는 설정에서 조정할 수 있습니다.",
    "helpTravelTime": "주행 시간",
    "helpTravelTimeText": "10 km/h 이상으로 주행하면 주행 시간이 시작됩니다. 2분 이상 10 km/h 미만이면 자동으로 정지합니다. 정체 모드에서는 이 시간이 1시간으로 연장됩니다. 자동 정지까지의 대기 시간은 주행 시간에서 차감됩니다. 주행 중에는 화면이 켜져 있고, 이후 평소대로 꺼질 수 있습니다.",
    "helpDistance": "거리",
    "helpDistanceText": "마지막 초기화 이후 총 주행 거리를 표시합니다 — 설정에 따라 킬로미터 또는 마일로 표시됩니다.",
    "helpAverageSpeed": "평균 속도",
    "helpAverageSpeedText": "평균 속도는 주행 거리와 주행 시간으로 계산됩니다.",
    "helpTrafficJam": "정체 모드",
    "helpTrafficJamText": "교통 체증 시 정체 모드를 활성화하세요. 자동 정지 시간이 2분에서 1시간으로 연장됩니다.",
    "helpStop": "정지",
    "helpStopText": "목적지에 도착했을 때 등 주행 시간을 즉시 수동으로 정지합니다.",
    "helpVehicles": "차량",
    "helpVehiclesText": "여러 차량을 만들 수 있습니다. 설정에서 좌우로 스와이프하여 차량 간 전환하고 \"차량 추가\"로 새 차량을 만드세요. 각 차량에는 이름(기본값 \"차량 #x\")과 출력, 질량, 전면 면적, 구동 방식 등의 매개변수가 있습니다. 출력은 kW, PS 또는 HP로 입력할 수 있습니다. 여러 차량이 있으면 상단 중앙의 차량 이름으로 활성 차량을 선택합니다.",
    "helpSettings": "설정",
    "helpSettingsText": "오른쪽 상단의 톱니바퀴 아이콘으로 기준 속도를 조정하고, km/h와 mph를 전환하고, 차량을 관리할 수 있습니다.",
    "helpBackground": "백그라운드",
    "helpBackgroundText": "다른 앱을 사용할 때도 앱이 백그라운드에서 계속 실행되어 속도와 절약 시간을 추적합니다. 주행하지 않을 때는 자동으로 GPS 정확도를 낮추어 배터리를 절약합니다.",
    "help": "도움말",
    "kmhUnit": "km/h",
]

// MARK: - Spanish

private let spanish: [String: String] = [
    "trafficJamMode": "Modo atasco",
    "stop": "Parar",
    "reset": "Reiniciar",

    "referenceFormat": "Referencia: %d %@",
    "timeSaved": "Tiempo ahorrado",
    "travelTime": "Tiempo de viaje",
    "distance": "Distancia",
    "average": "Promedio",
    "extraConsumptionFormat": "Consumo extra ≳%@ %%",
    "workFormat": "Trabajo: %@ / %@ kWh",
    "mehrverbrauchHelp": "Estima aproximadamente cuánto combustible o energía adicional consumes al superar la velocidad de referencia. El cálculo considera la resistencia aerodinámica, la resistencia a la rodadura, los cambios de altitud y la aceleración. Como no se capturan factores reales como la selección de marchas, las condiciones de viento, la eficiencia del motor y la presión de los neumáticos, el valor es solo orientativo.",
    "arbeitHelp": "Trabajo mecánico en kWh: trabajo realizado / trabajo a velocidad de referencia constante. El cociente da el consumo extra.",

    "referenceSpeed": "Velocidad de referencia",
    "referenceFooterFormat": "El ahorro de tiempo se calcula al conducir más rápido que %d %@.",
    "unit": "Unidad",
    "powerDisplay": "Indicador de potencia",
    "powerDisplayFooter": "Muestra el arco de potencia y las marcas de escala en el anillo de velocidad.",
    "vehicle": "Vehículo",
    "vehicleSwipeHint": "Desliza lateralmente para cambiar entre vehículos o añadir uno nuevo.",
    "deleteVehicle": "Eliminar este vehículo",
    "settings": "Ajustes",
    "done": "Listo",
    "name": "Nombre",
    "power": "Potencia",
    "measured": "Medido",
    "vehicleMass": "Masa del vehículo",
    "frontalArea": "Área frontal",
    "dragCoefficient": "Coef. aerodinámico",
    "rollingResistance": "Resistencia a la rodadura",
    "electricVehicle": "Vehículo eléctrico",
    "regenEfficiency": "Eficiencia de regeneración",
    "addVehicle": "Añadir vehículo",
    "language": "Idioma",
    "vehicleDefaultName": "Coche #%d",

    "helpTitle": "¿Merece la pena?",
    "helpSubtitleOr": "–o–",
    "helpSubtitleFull": "¿Realmente ahorré tanto tiempo?",
    "helpSpeed": "Velocidad",
    "helpSpeedText": "La app muestra tu velocidad actual por GPS — en km/h o mph, según tu configuración.",
    "helpPower": "Potencia instantánea",
    "helpPowerText": "El arco de color dentro del anillo de velocidad muestra la potencia actual del motor. Está escalado al vehículo activo: a plena potencia (potencia del vehículo × 85% de eficiencia del tren motriz) el arco alcanza el final del anillo gris. El arco rojo (a la derecha) muestra el trabajo realizado; el verde (a la izquierda) muestra el frenado. En vehículos eléctricos, el verde brillante indica la parte recuperada mediante frenado regenerativo. Las marcas se adaptan automáticamente al rango de potencia del vehículo. La mayor potencia medida se guarda por vehículo en Ajustes y puede adoptarse como potencia nominal o reiniciarse allí.",
    "helpTimeSaved": "Tiempo ahorrado",
    "helpTimeSavedText": "Cada vez que conduces más rápido que la velocidad de referencia establecida, la app calcula cuánto tiempo ahorras en comparación. El tiempo por debajo de la referencia no se resta.",
    "helpExtraConsumption": "Consumo extra",
    "helpExtraConsumptionText": "Estima aproximadamente cuánto combustible o energía adicional consumes al superar la velocidad de referencia. El cálculo considera la resistencia aerodinámica, la resistencia a la rodadura, los cambios de altitud y la aceleración. Como no se capturan factores reales, el valor es solo orientativo. Los parámetros del vehículo activo (masa, área frontal, coeficiente aerodinámico, etc.) pueden ajustarse en los Ajustes.",
    "helpTravelTime": "Tiempo de viaje",
    "helpTravelTimeText": "El tiempo de viaje comienza cuando superas los 10 km/h. Se detiene automáticamente si permaneces por debajo de 10 km/h durante más de dos minutos. En modo atasco, este tiempo se extiende a una hora. El tiempo de espera hasta la parada automática se resta del tiempo de viaje. Durante la conducción, la pantalla permanece encendida; después puede apagarse normalmente.",
    "helpDistance": "Distancia",
    "helpDistanceText": "Muestra la distancia total recorrida desde el último reinicio — en kilómetros o millas, según tu configuración.",
    "helpAverageSpeed": "Velocidad media",
    "helpAverageSpeedText": "La velocidad media se calcula a partir de la distancia recorrida y el tiempo de viaje.",
    "helpTrafficJam": "Modo atasco",
    "helpTrafficJamText": "Activa el modo atasco cuando estés en un atasco. El tiempo de parada automática se extiende de dos minutos a una hora.",
    "helpStop": "Parar",
    "helpStopText": "Detiene el tiempo de viaje inmediatamente, p. ej. cuando has llegado a tu destino.",
    "helpVehicles": "Vehículos",
    "helpVehiclesText": "Puedes crear múltiples vehículos. En Ajustes, desliza lateralmente entre vehículos y usa \"Añadir vehículo\" para crear otro. Cada vehículo tiene un nombre (por defecto \"Coche #x\") y sus propios parámetros como potencia, masa, área frontal y tipo de propulsión. La potencia puede introducirse en kW, PS o HP. Cuando hay múltiples vehículos, seleccionas el activo en la parte superior central mediante el nombre del vehículo.",
    "helpSettings": "Ajustes",
    "helpSettingsText": "Mediante el icono de engranaje en la esquina superior derecha puedes ajustar la velocidad de referencia, cambiar entre km/h y mph, y gestionar tus vehículos.",
    "helpBackground": "Segundo plano",
    "helpBackgroundText": "La app sigue funcionando en segundo plano, registrando velocidad y tiempo ahorrado incluso cuando usas otra app. Cuando no conduces, la app reduce automáticamente la precisión GPS para ahorrar batería.",
    "help": "Ayuda",
    "kmhUnit": "km/h",
]

// MARK: - Italian

private let italian: [String: String] = [
    "trafficJamMode": "Modo traffico",
    "stop": "Stop",
    "reset": "Reset",

    "referenceFormat": "Riferimento: %d %@",
    "timeSaved": "Tempo risparmiato",
    "travelTime": "Tempo di viaggio",
    "distance": "Distanza",
    "average": "Media",
    "extraConsumptionFormat": "Consumo extra ≳%@ %%",
    "workFormat": "Lavoro: %@ / %@ kWh",
    "mehrverbrauchHelp": "Stima approssimativamente quanto carburante o energia in più consumi superando la velocità di riferimento. Il calcolo considera la resistenza aerodinamica, la resistenza al rotolamento, le variazioni di quota e l'accelerazione. Poiché fattori reali come la selezione del cambio, le condizioni del vento, l'efficienza del motore e la pressione dei pneumatici non vengono considerati, il valore è solo indicativo.",
    "arbeitHelp": "Lavoro meccanico in kWh: lavoro effettivo / lavoro a velocità di riferimento costante. Il quoziente indica il consumo extra.",

    "referenceSpeed": "Velocità di riferimento",
    "referenceFooterFormat": "Il risparmio di tempo viene calcolato quando si guida più veloce di %d %@.",
    "unit": "Unità",
    "powerDisplay": "Indicatore di potenza",
    "powerDisplayFooter": "Mostra l'arco di potenza e i segni di scala nell'anello della velocità.",
    "vehicle": "Veicolo",
    "vehicleSwipeHint": "Scorri lateralmente per passare da un veicolo all'altro o aggiungerne uno nuovo.",
    "deleteVehicle": "Elimina questo veicolo",
    "settings": "Impostazioni",
    "done": "Fatto",
    "name": "Nome",
    "power": "Potenza",
    "measured": "Misurato",
    "vehicleMass": "Massa del veicolo",
    "frontalArea": "Area frontale",
    "dragCoefficient": "Coeff. aerodinamico",
    "rollingResistance": "Resistenza al rotolamento",
    "electricVehicle": "Veicolo elettrico",
    "regenEfficiency": "Efficienza rigenerativa",
    "addVehicle": "Aggiungi veicolo",
    "language": "Lingua",
    "vehicleDefaultName": "Auto #%d",

    "helpTitle": "Ne vale la pena?",
    "helpSubtitleOr": "–oppure–",
    "helpSubtitleFull": "Ho davvero risparmiato così tanto tempo?",
    "helpSpeed": "Velocità",
    "helpSpeedText": "L'app mostra la tua velocità attuale tramite GPS — in km/h o mph, a seconda dell'impostazione.",
    "helpPower": "Potenza istantanea",
    "helpPowerText": "L'arco colorato all'interno dell'anello della velocità mostra la potenza attuale del motore. È scalato sul veicolo attivo: a piena potenza (potenza del veicolo × 85% di efficienza del treno motore) l'arco raggiunge la fine dell'anello grigio. L'arco rosso (a destra) mostra il lavoro svolto; il verde (a sinistra) mostra la frenata. Per i veicoli elettrici, il verde brillante indica la parte recuperata tramite frenata rigenerativa. I segni si adattano automaticamente alla gamma di potenza del veicolo. La massima potenza misurata viene salvata per veicolo nelle Impostazioni e può essere adottata come potenza nominale o azzerata.",
    "helpTimeSaved": "Tempo risparmiato",
    "helpTimeSavedText": "Ogni volta che guidi più veloce della velocità di riferimento impostata, l'app calcola quanto tempo risparmi rispetto alla velocità di riferimento. Il tempo sotto il riferimento non viene sottratto.",
    "helpExtraConsumption": "Consumo extra",
    "helpExtraConsumptionText": "Stima approssimativamente quanto carburante o energia in più consumi superando la velocità di riferimento. Il calcolo considera resistenza aerodinamica, resistenza al rotolamento, variazioni di quota e accelerazione. Poiché fattori reali non vengono considerati, il valore è solo indicativo. I parametri del veicolo attivo (massa, area frontale, coefficiente aerodinamico, ecc.) possono essere regolati nelle Impostazioni.",
    "helpTravelTime": "Tempo di viaggio",
    "helpTravelTimeText": "Il tempo di viaggio inizia quando superi i 10 km/h. Si ferma automaticamente se rimani sotto i 10 km/h per più di due minuti. In modo traffico questo tempo viene esteso a un'ora. Il tempo di attesa viene sottratto dal tempo di viaggio. Durante la guida lo schermo resta acceso; dopo può spegnersi normalmente.",
    "helpDistance": "Distanza",
    "helpDistanceText": "Mostra la distanza totale percorsa dall'ultimo reset — in chilometri o miglia, a seconda dell'impostazione.",
    "helpAverageSpeed": "Velocità media",
    "helpAverageSpeedText": "La velocità media viene calcolata dalla distanza percorsa e dal tempo di viaggio.",
    "helpTrafficJam": "Modo traffico",
    "helpTrafficJamText": "Attiva il modo traffico quando sei nel traffico. Il tempo di arresto automatico viene esteso da due minuti a un'ora.",
    "helpStop": "Stop",
    "helpStopText": "Ferma immediatamente il tempo di viaggio, ad es. quando sei arrivato a destinazione.",
    "helpVehicles": "Veicoli",
    "helpVehiclesText": "Puoi creare più veicoli. Nelle Impostazioni, scorri lateralmente tra i veicoli e usa \"Aggiungi veicolo\" per crearne un altro. Ogni veicolo ha un nome (predefinito \"Auto #x\") e propri parametri come potenza, massa, area frontale e tipo di propulsione. La potenza può essere inserita in kW, PS o HP. Quando ci sono più veicoli, selezioni quello attivo in alto al centro tramite il nome del veicolo.",
    "helpSettings": "Impostazioni",
    "helpSettingsText": "Tramite l'icona dell'ingranaggio in alto a destra puoi regolare la velocità di riferimento, passare tra km/h e mph e gestire i tuoi veicoli.",
    "helpBackground": "Sfondo",
    "helpBackgroundText": "L'app continua a funzionare in background, registrando velocità e tempo risparmiato anche quando usi un'altra app. Quando non guidi, l'app riduce automaticamente la precisione GPS per risparmiare batteria.",
    "help": "Aiuto",
    "kmhUnit": "km/h",
]

// MARK: - Dutch

private let dutch: [String: String] = [
    "trafficJamMode": "Filestand",
    "stop": "Stop",
    "reset": "Reset",

    "referenceFormat": "Referentie: %d %@",
    "timeSaved": "Bespaarde tijd",
    "travelTime": "Reistijd",
    "distance": "Afstand",
    "average": "Gemiddelde",
    "extraConsumptionFormat": "Meerverbruik ≳%@ %%",
    "workFormat": "Arbeid: %@ / %@ kWh",
    "mehrverbrauchHelp": "Schat ruwweg hoeveel extra brandstof of energie je verbruikt door sneller te rijden dan de referentiesnelheid. De berekening houdt rekening met luchtweerstand, rolweerstand, hoogteverschillen en versnelling. Omdat echte factoren zoals versnellingskeuze, windcondities, motorrendement en bandenspanning niet worden meegenomen, is de waarde slechts een indicatie.",
    "arbeitHelp": "Mechanische arbeid in kWh: werkelijk geleverde arbeid / arbeid bij constante referentiesnelheid. Het quotiënt geeft het meerverbruik.",

    "referenceSpeed": "Referentiesnelheid",
    "referenceFooterFormat": "Tijdsbesparing wordt berekend bij sneller rijden dan %d %@.",
    "unit": "Eenheid",
    "powerDisplay": "Vermogensweergave",
    "powerDisplayFooter": "Toont de vermogensboog en schaalmarkeringen in de snelheidsring.",
    "vehicle": "Voertuig",
    "vehicleSwipeHint": "Veeg opzij om tussen voertuigen te wisselen of een nieuw toe te voegen.",
    "deleteVehicle": "Dit voertuig verwijderen",
    "settings": "Instellingen",
    "done": "Klaar",
    "name": "Naam",
    "power": "Vermogen",
    "measured": "Gemeten",
    "vehicleMass": "Voertuigmassa",
    "frontalArea": "Frontaal oppervlak",
    "dragCoefficient": "Luchtweerstandscoëff.",
    "rollingResistance": "Rolweerstand",
    "electricVehicle": "Elektrisch voertuig",
    "regenEfficiency": "Regeneratie-efficiëntie",
    "addVehicle": "Voertuig toevoegen",
    "language": "Taal",
    "vehicleDefaultName": "Auto #%d",

    "helpTitle": "Is het de moeite waard?",
    "helpSubtitleOr": "–of–",
    "helpSubtitleFull": "Heb ik echt zoveel tijd bespaard?",
    "helpSpeed": "Snelheid",
    "helpSpeedText": "De app toont je huidige GPS-snelheid — in km/h of mph, afhankelijk van je instelling.",
    "helpPower": "Momentaan vermogen",
    "helpPowerText": "De gekleurde boog in de snelheidsring toont het huidige motorvermogen. Het is geschaald naar het actieve voertuig: bij vol vermogen (voertuigvermogen × 85% aandrijflijnrendement) reikt de boog tot het einde van de grijze ring. De rode boog (rechts) toont geleverde arbeid; groen (links) toont remmen. Bij elektrische voertuigen geeft helder groen het door regeneratief remmen teruggewonnen deel aan. De markeringen passen zich automatisch aan het vermogensbereik van het voertuig aan. Het hoogst gemeten motorvermogen wordt per voertuig opgeslagen in Instellingen en kan daar als nominaal vermogen worden overgenomen of gereset.",
    "helpTimeSaved": "Bespaarde tijd",
    "helpTimeSavedText": "Telkens wanneer je sneller rijdt dan de ingestelde referentiesnelheid, berekent de app hoeveel tijd je bespaart ten opzichte van de referentiesnelheid. Tijd onder de referentie wordt niet afgetrokken.",
    "helpExtraConsumption": "Meerverbruik",
    "helpExtraConsumptionText": "Schat ruwweg hoeveel extra brandstof of energie je verbruikt door de referentiesnelheid te overschrijden. De berekening houdt rekening met luchtweerstand, rolweerstand, hoogteverschillen en versnelling. Omdat echte factoren niet worden meegenomen, is de waarde slechts een indicatie. De parameters van het actieve voertuig (massa, frontaal oppervlak, luchtweerstandscoëfficiënt, enz.) kunnen in de Instellingen worden aangepast.",
    "helpTravelTime": "Reistijd",
    "helpTravelTimeText": "De reistijd begint zodra je sneller dan 10 km/h rijdt. Hij stopt automatisch als je langer dan twee minuten onder 10 km/h blijft. In filestand wordt deze tijd verlengd tot één uur. De wachttijd tot automatische stop wordt afgetrokken van de reistijd. Tijdens het rijden blijft het scherm aan; daarna kan het normaal uitschakelen.",
    "helpDistance": "Afstand",
    "helpDistanceText": "Toont de totale gereden afstand sinds de laatste reset — in kilometers of mijlen, afhankelijk van je instelling.",
    "helpAverageSpeed": "Gemiddelde snelheid",
    "helpAverageSpeedText": "De gemiddelde snelheid wordt berekend uit de gereden afstand en de reistijd.",
    "helpTrafficJam": "Filestand",
    "helpTrafficJamText": "Activeer de filestand wanneer je in de file staat. De automatische stoptijd wordt dan verlengd van twee minuten naar één uur.",
    "helpStop": "Stop",
    "helpStopText": "Stopt de reistijd onmiddellijk, bijv. wanneer je op je bestemming bent aangekomen.",
    "helpVehicles": "Voertuigen",
    "helpVehiclesText": "Je kunt meerdere voertuigen aanmaken. In Instellingen veeg je zijwaarts tussen voertuigen en gebruik je \"Voertuig toevoegen\" om er nog een aan te maken. Elk voertuig heeft een naam (standaard \"Auto #x\") en eigen parameters zoals vermogen, massa, frontaal oppervlak en aandrijftype. Vermogen kan worden ingevoerd in kW, PS of HP. Bij meerdere voertuigen selecteer je het actieve bovenaan in het midden via de voertuignaam.",
    "helpSettings": "Instellingen",
    "helpSettingsText": "Via het tandwielpictogram rechtsboven kun je de referentiesnelheid aanpassen, wisselen tussen km/h en mph, en je voertuigen beheren.",
    "helpBackground": "Achtergrond",
    "helpBackgroundText": "De app blijft op de achtergrond draaien en registreert snelheid en bespaarde tijd, ook als je een andere app gebruikt. Wanneer je niet rijdt, verlaagt de app automatisch de GPS-nauwkeurigheid om batterij te besparen.",
    "help": "Help",
    "kmhUnit": "km/h",
]

// MARK: - French

private let french: [String: String] = [
    "trafficJamMode": "Mode embouteillage",
    "stop": "Arrêter",
    "reset": "Réinitialiser",

    "referenceFormat": "Référence : %d %@",
    "timeSaved": "Temps économisé",
    "travelTime": "Temps de trajet",
    "distance": "Distance",
    "average": "Moyenne",
    "extraConsumptionFormat": "Surconsommation ≳%@ %%",
    "workFormat": "Travail : %@ / %@ kWh",
    "mehrverbrauchHelp": "Estime approximativement la quantité de carburant ou d'énergie supplémentaire consommée en dépassant la vitesse de référence. Le calcul prend en compte la résistance aérodynamique, la résistance au roulement, les changements d'altitude et l'accélération. Les facteurs réels comme le choix de rapport, les conditions de vent, le rendement du moteur et la pression des pneus n'étant pas pris en compte, la valeur n'est qu'indicative.",
    "arbeitHelp": "Travail mécanique en kWh : travail effectué / travail à vitesse de référence constante. Le quotient donne la surconsommation.",

    "referenceSpeed": "Vitesse de référence",
    "referenceFooterFormat": "Le gain de temps est calculé lorsque vous roulez plus vite que %d %@.",
    "unit": "Unité",
    "powerDisplay": "Affichage de puissance",
    "powerDisplayFooter": "Affiche l'arc de puissance et les graduations dans l'anneau de vitesse.",
    "vehicle": "Véhicule",
    "vehicleSwipeHint": "Balayez latéralement pour changer de véhicule ou en ajouter un nouveau.",
    "deleteVehicle": "Supprimer ce véhicule",
    "settings": "Réglages",
    "done": "Terminé",
    "name": "Nom",
    "power": "Puissance",
    "measured": "Mesuré",
    "vehicleMass": "Masse du véhicule",
    "frontalArea": "Surface frontale",
    "dragCoefficient": "Coeff. aérodynamique",
    "rollingResistance": "Résistance au roulement",
    "electricVehicle": "Véhicule électrique",
    "regenEfficiency": "Efficacité régénérative",
    "addVehicle": "Ajouter un véhicule",
    "language": "Langue",
    "vehicleDefaultName": "Voiture #%d",

    "helpTitle": "Est-ce que ça vaut le coup ?",
    "helpSubtitleOr": "–ou–",
    "helpSubtitleFull": "Ai-je vraiment économisé autant de temps ?",
    "helpSpeed": "Vitesse",
    "helpSpeedText": "L'app affiche votre vitesse actuelle par GPS — en km/h ou mph, selon votre réglage.",
    "helpPower": "Puissance instantanée",
    "helpPowerText": "L'arc coloré à l'intérieur de l'anneau de vitesse montre la puissance actuelle du moteur. Il est mis à l'échelle du véhicule actif : à pleine puissance (puissance du véhicule × 85 % de rendement de la transmission), l'arc atteint l'extrémité de l'anneau gris. L'arc rouge (à droite) montre le travail effectué ; le vert (à gauche) montre le freinage. Pour les véhicules électriques, le vert vif indique la partie récupérée par freinage régénératif. Les graduations s'adaptent automatiquement à la plage de puissance du véhicule. La puissance maximale mesurée est enregistrée par véhicule dans les Réglages et peut y être adoptée comme puissance nominale ou réinitialisée.",
    "helpTimeSaved": "Temps économisé",
    "helpTimeSavedText": "Chaque fois que vous roulez plus vite que la vitesse de référence définie, l'app calcule le temps économisé par rapport à cette vitesse. Le temps en dessous de la référence n'est pas soustrait.",
    "helpExtraConsumption": "Surconsommation",
    "helpExtraConsumptionText": "Estime approximativement la quantité de carburant ou d'énergie supplémentaire consommée en dépassant la vitesse de référence. Le calcul prend en compte la résistance aérodynamique, la résistance au roulement, les changements d'altitude et l'accélération. Les facteurs réels n'étant pas pris en compte, la valeur n'est qu'indicative. Les paramètres du véhicule actif (masse, surface frontale, coefficient aérodynamique, etc.) peuvent être ajustés dans les Réglages.",
    "helpTravelTime": "Temps de trajet",
    "helpTravelTimeText": "Le temps de trajet commence dès que vous dépassez 10 km/h. Il s'arrête automatiquement si vous restez en dessous de 10 km/h pendant plus de deux minutes. En mode embouteillage, ce délai est prolongé à une heure. Le temps d'attente est soustrait du temps de trajet. Pendant la conduite, l'écran reste allumé ; ensuite il peut s'éteindre normalement.",
    "helpDistance": "Distance",
    "helpDistanceText": "Affiche la distance totale parcourue depuis la dernière réinitialisation — en kilomètres ou miles, selon votre réglage.",
    "helpAverageSpeed": "Vitesse moyenne",
    "helpAverageSpeedText": "La vitesse moyenne est calculée à partir de la distance parcourue et du temps de trajet.",
    "helpTrafficJam": "Mode embouteillage",
    "helpTrafficJamText": "Activez le mode embouteillage quand vous êtes dans un embouteillage. Le temps d'arrêt automatique passe de deux minutes à une heure.",
    "helpStop": "Arrêter",
    "helpStopText": "Arrête immédiatement le temps de trajet, par ex. quand vous êtes arrivé à destination.",
    "helpVehicles": "Véhicules",
    "helpVehiclesText": "Vous pouvez créer plusieurs véhicules. Dans les Réglages, balayez latéralement entre les véhicules et utilisez « Ajouter un véhicule » pour en créer un autre. Chaque véhicule a un nom (par défaut « Voiture #x ») et ses propres paramètres comme la puissance, la masse, la surface frontale et le type de motorisation. La puissance peut être saisie en kW, PS ou HP. S'il y a plusieurs véhicules, vous sélectionnez celui actif en haut au centre via le nom du véhicule.",
    "helpSettings": "Réglages",
    "helpSettingsText": "Via l'icône d'engrenage en haut à droite, vous pouvez ajuster la vitesse de référence, basculer entre km/h et mph, et gérer vos véhicules.",
    "helpBackground": "Arrière-plan",
    "helpBackgroundText": "L'app continue de fonctionner en arrière-plan, enregistrant la vitesse et le temps économisé même lorsque vous utilisez une autre app. Quand vous ne conduisez pas, l'app réduit automatiquement la précision GPS pour économiser la batterie.",
    "help": "Aide",
    "kmhUnit": "km/h",
]

// MARK: - Romanian

private let romanian: [String: String] = [
    "trafficJamMode": "Mod ambuteiaj",
    "stop": "Stop",
    "reset": "Resetare",

    "referenceFormat": "Referință: %d %@",
    "timeSaved": "Timp economisit",
    "travelTime": "Timp de călătorie",
    "distance": "Distanță",
    "average": "Medie",
    "extraConsumptionFormat": "Consum suplimentar ≳%@ %%",
    "workFormat": "Lucru: %@ / %@ kWh",
    "mehrverbrauchHelp": "Estimează aproximativ cât combustibil sau energie suplimentară consumi depășind viteza de referință. Calculul ia în considerare rezistența aerodinamică, rezistența la rulare, diferențele de altitudine și accelerația. Deoarece factorii reali precum alegerea treptei de viteză, condițiile de vânt, eficiența motorului și presiunea pneurilor nu sunt captați, valoarea este doar orientativă.",
    "arbeitHelp": "Lucru mecanic în kWh: lucrul efectiv / lucrul la viteza de referință constantă. Câtul reprezintă consumul suplimentar.",

    "referenceSpeed": "Viteza de referință",
    "referenceFooterFormat": "Economia de timp se calculează când conduci mai repede de %d %@.",
    "unit": "Unitate",
    "powerDisplay": "Afișaj putere",
    "powerDisplayFooter": "Afișează arcul de putere și marcajele de scală în inelul de viteză.",
    "vehicle": "Vehicul",
    "vehicleSwipeHint": "Glisează lateral pentru a comuta între vehicule sau a adăuga unul nou.",
    "deleteVehicle": "Șterge acest vehicul",
    "settings": "Setări",
    "done": "Gata",
    "name": "Nume",
    "power": "Putere",
    "measured": "Măsurat",
    "vehicleMass": "Masa vehiculului",
    "frontalArea": "Suprafața frontală",
    "dragCoefficient": "Coef. aerodinamic",
    "rollingResistance": "Rezistența la rulare",
    "electricVehicle": "Vehicul electric",
    "regenEfficiency": "Eficiență regenerativă",
    "addVehicle": "Adaugă vehicul",
    "language": "Limbă",
    "vehicleDefaultName": "Mașină #%d",

    "helpTitle": "Merită?",
    "helpSubtitleOr": "–sau–",
    "helpSubtitleFull": "Chiar am economisit atât de mult timp?",
    "helpSpeed": "Viteză",
    "helpSpeedText": "Aplicația afișează viteza ta curentă prin GPS — în km/h sau mph, în funcție de setare.",
    "helpPower": "Putere instantanee",
    "helpPowerText": "Arcul colorat din interiorul inelului de viteză arată puterea curentă a motorului. Este scalat la vehiculul activ: la putere maximă (puterea vehiculului × 85% eficiența transmisiei) arcul ajunge la capătul inelului gri. Arcul roșu (spre dreapta) arată lucrul efectuat; verdele (spre stânga) arată frânarea. La vehiculele electrice, verdele deschis indică partea recuperată prin frânare regenerativă. Marcajele se adaptează automat la gama de putere a vehiculului. Puterea maximă măsurată este salvată per vehicul în Setări și poate fi adoptată ca putere nominală sau resetată acolo.",
    "helpTimeSaved": "Timp economisit",
    "helpTimeSavedText": "De fiecare dată când conduci mai repede decât viteza de referință setată, aplicația calculează cât timp economisești comparativ. Timpul sub referință nu este scăzut.",
    "helpExtraConsumption": "Consum suplimentar",
    "helpExtraConsumptionText": "Estimează aproximativ cât combustibil sau energie suplimentară consumi depășind viteza de referință. Calculul ia în considerare rezistența aerodinamică, rezistența la rulare, diferențele de altitudine și accelerația. Deoarece factorii reali nu sunt captați, valoarea este doar orientativă. Parametrii vehiculului activ (masa, suprafața frontală, coeficientul aerodinamic etc.) pot fi ajustați în Setări.",
    "helpTravelTime": "Timp de călătorie",
    "helpTravelTimeText": "Timpul de călătorie începe când depășești 10 km/h. Se oprește automat dacă rămâi sub 10 km/h mai mult de două minute. În modul ambuteiaj, acest timp se prelungește la o oră. Timpul de așteptare este scăzut din timpul de călătorie. În timpul conducerii, ecranul rămâne aprins; după aceea se poate stinge normal.",
    "helpDistance": "Distanță",
    "helpDistanceText": "Afișează distanța totală parcursă de la ultima resetare — în kilometri sau mile, în funcție de setare.",
    "helpAverageSpeed": "Viteza medie",
    "helpAverageSpeedText": "Viteza medie este calculată din distanța parcursă și timpul de călătorie.",
    "helpTrafficJam": "Mod ambuteiaj",
    "helpTrafficJamText": "Activează modul ambuteiaj când ești blocat în trafic. Timpul de oprire automată se prelungește de la două minute la o oră.",
    "helpStop": "Stop",
    "helpStopText": "Oprește imediat timpul de călătorie, de ex. când ai ajuns la destinație.",
    "helpVehicles": "Vehicule",
    "helpVehiclesText": "Poți crea mai multe vehicule. În Setări, glisează lateral între vehicule și folosește \u{201E}Adaugă vehicul\u{201C} pentru a crea altul. Fiecare vehicul are un nume (implicit \u{201E}Mașină #x\u{201C}) și proprii parametri precum puterea, masa, suprafața frontală și tipul de propulsie. Puterea poate fi introdusă în kW, PS sau HP. Când există mai multe vehicule, selectezi vehiculul activ în partea de sus, în centru, prin numele vehiculului.",
    "helpSettings": "Setări",
    "helpSettingsText": "Prin pictograma roții dințate din dreapta sus poți ajusta viteza de referință, comuta între km/h și mph și gestiona vehiculele tale.",
    "helpBackground": "Fundal",
    "helpBackgroundText": "Aplicația continuă să funcționeze în fundal, înregistrând viteza și timpul economisit chiar și când folosești altă aplicație. Când nu conduci, aplicația reduce automat precizia GPS pentru a economisi bateria.",
    "help": "Ajutor",
    "kmhUnit": "km/h",
]

// MARK: - Portuguese

private let portuguese: [String: String] = [
    "trafficJamMode": "Modo engarrafamento",
    "stop": "Parar",
    "reset": "Reiniciar",

    "referenceFormat": "Referência: %d %@",
    "timeSaved": "Tempo poupado",
    "travelTime": "Tempo de viagem",
    "distance": "Distância",
    "average": "Média",
    "extraConsumptionFormat": "Consumo extra ≳%@ %%",
    "workFormat": "Trabalho: %@ / %@ kWh",
    "mehrverbrauchHelp": "Estima aproximadamente quanto combustível ou energia adicional consomes ao ultrapassar a velocidade de referência. O cálculo considera a resistência aerodinâmica, a resistência ao rolamento, as variações de altitude e a aceleração. Como fatores reais como a seleção de mudanças, condições de vento, eficiência do motor e pressão dos pneus não são considerados, o valor é apenas indicativo.",
    "arbeitHelp": "Trabalho mecânico em kWh: trabalho realizado / trabalho a velocidade de referência constante. O quociente indica o consumo extra.",

    "referenceSpeed": "Velocidade de referência",
    "referenceFooterFormat": "A poupança de tempo é calculada ao conduzir mais rápido que %d %@.",
    "unit": "Unidade",
    "powerDisplay": "Indicador de potência",
    "powerDisplayFooter": "Mostra o arco de potência e as marcações de escala no anel de velocidade.",
    "vehicle": "Veículo",
    "vehicleSwipeHint": "Desliza lateralmente para alternar entre veículos ou adicionar um novo.",
    "deleteVehicle": "Eliminar este veículo",
    "settings": "Definições",
    "done": "Concluído",
    "name": "Nome",
    "power": "Potência",
    "measured": "Medido",
    "vehicleMass": "Massa do veículo",
    "frontalArea": "Área frontal",
    "dragCoefficient": "Coef. aerodinâmico",
    "rollingResistance": "Resistência ao rolamento",
    "electricVehicle": "Veículo elétrico",
    "regenEfficiency": "Eficiência regenerativa",
    "addVehicle": "Adicionar veículo",
    "language": "Idioma",
    "vehicleDefaultName": "Carro #%d",

    "helpTitle": "Vale a pena?",
    "helpSubtitleOr": "–ou–",
    "helpSubtitleFull": "Será que realmente poupo assim tanto tempo?",
    "helpSpeed": "Velocidade",
    "helpSpeedText": "A app mostra a tua velocidade atual por GPS — em km/h ou mph, conforme a definição.",
    "helpPower": "Potência instantânea",
    "helpPowerText": "O arco colorido dentro do anel de velocidade mostra a potência atual do motor. Está dimensionado para o veículo ativo: a potência máxima (potência do veículo × 85% de eficiência da transmissão) o arco alcança o fim do anel cinzento. O arco vermelho (à direita) mostra o trabalho realizado; o verde (à esquerda) mostra a travagem. Em veículos elétricos, o verde brilhante indica a parte recuperada por travagem regenerativa. As marcações adaptam-se automaticamente à gama de potência do veículo. A potência máxima medida é guardada por veículo nas Definições e pode ser adotada como potência nominal ou reposta.",
    "helpTimeSaved": "Tempo poupado",
    "helpTimeSavedText": "Sempre que conduzes mais rápido que a velocidade de referência definida, a app calcula quanto tempo poupas em comparação. O tempo abaixo da referência não é subtraído.",
    "helpExtraConsumption": "Consumo extra",
    "helpExtraConsumptionText": "Estima aproximadamente quanto combustível ou energia adicional consomes ao ultrapassar a velocidade de referência. O cálculo considera a resistência aerodinâmica, resistência ao rolamento, variações de altitude e aceleração. Como fatores reais não são considerados, o valor é apenas indicativo. Os parâmetros do veículo ativo (massa, área frontal, coeficiente aerodinâmico, etc.) podem ser ajustados nas Definições.",
    "helpTravelTime": "Tempo de viagem",
    "helpTravelTimeText": "O tempo de viagem começa quando ultrapassas 10 km/h. Para automaticamente se ficares abaixo de 10 km/h por mais de dois minutos. Em modo engarrafamento, este tempo é estendido para uma hora. O tempo de espera é subtraído do tempo de viagem. Durante a condução, o ecrã permanece ligado; depois pode desligar-se normalmente.",
    "helpDistance": "Distância",
    "helpDistanceText": "Mostra a distância total percorrida desde a última reinicialização — em quilómetros ou milhas, conforme a definição.",
    "helpAverageSpeed": "Velocidade média",
    "helpAverageSpeedText": "A velocidade média é calculada a partir da distância percorrida e do tempo de viagem.",
    "helpTrafficJam": "Modo engarrafamento",
    "helpTrafficJamText": "Ativa o modo engarrafamento quando estiveres no trânsito. O tempo de paragem automática é estendido de dois minutos para uma hora.",
    "helpStop": "Parar",
    "helpStopText": "Para imediatamente o tempo de viagem, por ex. quando chegaste ao teu destino.",
    "helpVehicles": "Veículos",
    "helpVehiclesText": "Podes criar vários veículos. Nas Definições, desliza lateralmente entre veículos e usa \"Adicionar veículo\" para criar outro. Cada veículo tem um nome (por defeito \"Carro #x\") e os seus próprios parâmetros como potência, massa, área frontal e tipo de propulsão. A potência pode ser introduzida em kW, PS ou HP. Quando existem vários veículos, selecionas o ativo no topo ao centro através do nome do veículo.",
    "helpSettings": "Definições",
    "helpSettingsText": "Através do ícone de engrenagem no canto superior direito podes ajustar a velocidade de referência, alternar entre km/h e mph e gerir os teus veículos.",
    "helpBackground": "Segundo plano",
    "helpBackgroundText": "A app continua a funcionar em segundo plano, registando velocidade e tempo poupado mesmo quando usas outra app. Quando não conduzes, a app reduz automaticamente a precisão GPS para poupar bateria.",
    "help": "Ajuda",
    "kmhUnit": "km/h",
]
